import { execFileSync } from "node:child_process";
import fs from "node:fs";

const generatedPath = "src/generated/rust-contracts.ts";
const generated = fs.readFileSync(generatedPath, "utf8");
const required = [
  "export type ApiError",
  "export type AppSettingsDto",
  "hostOperationLogPopups: boolean",
  "export type AppUpdateStatusDto",
  "export type HostDto",
  "export type ProfileDto",
  "export type SkillPackDto",
  "export type NetworkProxyStatusDto",
  "export type SshBootstrapResultDto",
  "export type SshConfigDeleteResultDto",
  "export type HostResourceBatchResultDto",
  "export type TaskStepStatus",
  '"pending" | "running" | "success" | "failed" | "skipped"',
  "export type TaskStep",
  "stepId: string",
  "export type TaskRun",
  "steps: Array<TaskStep>",
  "stepId?: string",
  '"interrupted"',
  "export type HostOperationKindDto",
  "export type HostOperationProgressEventDto",
  'operation: HostOperationKindDto, step: TaskStep, log?: TaskLog',
  "export type RemoteProbeBatchItemDto",
  "result?: RemoteProbeResultDto, error?: string",
  "export type RemoteProbeBatchResultDto",
  "latestCodexVersion: LatestCodexVersionDto",
  "results: Array<RemoteProbeBatchItemDto>",
  "export type RemoteCodexBatchItemDto",
  "result?: RemoteCodexMaintenanceResultDto, error?: string",
  "export type RemoteCodexBatchResultDto",
  "action: RemoteCodexActionDto",
  "results: Array<RemoteCodexBatchItemDto>",
  "export type ProfileApplyBatchResultDto",
  "export type ProfileApplyPreviewDto",
  "export type StorageMigrationPlan"
];

for (const token of required) {
  if (!generated.includes(token)) throw new Error(`Generated Rust bindings are missing: ${token}`);
}
if (generated.includes("bigint")) {
  throw new Error("JSON wire bindings must use TypeScript number rather than bigint.");
}
if (!generated.startsWith("// Generated by `cargo test export_bindings`; do not edit.")) {
  throw new Error("Generated bindings are missing their source-of-truth header.");
}

// Verify the tracked/generated artifact against the current Rust source rather
// than HEAD, so intentional uncommitted contract work can still be validated.
execFileSync(
  "cargo",
  ["test", "--manifest-path", "src-tauri/Cargo.toml", "export_bindings", "--", "--nocapture"],
  { stdio: "inherit" }
);
const regenerated = fs.readFileSync(generatedPath, "utf8");
if (generated !== regenerated) {
  throw new Error("Rust bindings changed during verification. Regenerate src/generated/rust-contracts.ts and rerun the test.");
}

console.log("BINDINGS PASS: generated Rust wire contracts are usable and current.");
