import { execFileSync } from "node:child_process";
import fs from "node:fs";

const generatedPath = "src/generated/rust-contracts.ts";
const generated = fs.readFileSync(generatedPath, "utf8");
const required = [
  "export type ApiError",
  "export type AppSettingsDto",
  "export type AppUpdateStatusDto",
  "export type HostDto",
  "export type ProfileDto",
  "export type SkillPackDto",
  "export type NetworkProxyStatusDto",
  "export type SshBootstrapResultDto",
  "export type SshConfigDeleteResultDto",
  "export type HostResourceBatchResultDto",
  "export type TaskRun",
  '"interrupted"',
  "export type ProfileApplyBatchResultDto",
  "export type ProfileApplyPreviewDto",
  "export type StorageMigrationPlan"
];

for (const token of required) {
  if (!generated.includes(token)) throw new Error(`Generated Rust bindings are missing: ${token}`);
}
if (generated.includes("bigint")) {
  throw new Error("JSON wire bindings must use TypeScript number rather than bigint.");
}
if (!generated.startsWith("// Generated by `cargo test export_bindings`; do not edit.")) {
  throw new Error("Generated bindings are missing their source-of-truth header.");
}

// Once tracked, regeneration must leave the committed contract byte-for-byte clean.
let tracked = false;
try {
  execFileSync("git", ["ls-files", "--error-unmatch", generatedPath], { stdio: "ignore" });
  tracked = true;
} catch {
  // The first local generation is untracked until its foundation commit.
}
if (tracked) {
  try {
  execFileSync("git", ["diff", "--exit-code", "--", generatedPath], { stdio: "inherit" });
  } catch {
    throw new Error("Rust bindings drifted. Regenerate and commit src/generated/rust-contracts.ts.");
  }
}

console.log("BINDINGS PASS: generated Rust wire contracts are usable and current.");
